<?php
// This script and data application were generated by AppGini 23.16
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Supporters.php');
	include_once(__DIR__ . '/Supporters_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Supporters');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Supporters';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Supporters`.`ID`" => "ID",
		"`Supporters`.`FirstName`" => "FirstName",
		"`Supporters`.`LastName`" => "LastName",
		"`Supporters`.`SpouseName`" => "SpouseName",
		"`Supporters`.`Address1`" => "Address1",
		"`Supporters`.`Address2`" => "Address2",
		"`Supporters`.`City`" => "City",
		"`Supporters`.`State`" => "State",
		"`Supporters`.`Zip`" => "Zip",
		"if(CHAR_LENGTH(`Supporters`.`Country`)>20, concat(left(`Supporters`.`Country`,20),' ...'), `Supporters`.`Country`)" => "Country",
		"CONCAT_WS('-', LEFT(`Supporters`.`Phone`,3), MID(`Supporters`.`Phone`,4,3), RIGHT(`Supporters`.`Phone`,4))" => "Phone",
		"CONCAT_WS('-', LEFT(`Supporters`.`Cell`,3), MID(`Supporters`.`Cell`,4,3), RIGHT(`Supporters`.`Cell`,4))" => "Cell",
		"`Supporters`.`Email`" => "Email",
		"`Supporters`.`Status`" => "Status",
		"`Supporters`.`ContactMethod`" => "ContactMethod",
		"`Supporters`.`TotalDonated`" => "TotalDonated",
		"`Supporters`.`TotalMatched`" => "TotalMatched",
		"`Supporters`.`Name`" => "Name",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Supporters`.`ID`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => 15,
		16 => '`Supporters`.`TotalDonated`',
		17 => '`Supporters`.`TotalMatched`',
		18 => 18,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Supporters`.`ID`" => "ID",
		"`Supporters`.`FirstName`" => "FirstName",
		"`Supporters`.`LastName`" => "LastName",
		"`Supporters`.`SpouseName`" => "SpouseName",
		"`Supporters`.`Address1`" => "Address1",
		"`Supporters`.`Address2`" => "Address2",
		"`Supporters`.`City`" => "City",
		"`Supporters`.`State`" => "State",
		"`Supporters`.`Zip`" => "Zip",
		"`Supporters`.`Country`" => "Country",
		"CONCAT_WS('-', LEFT(`Supporters`.`Phone`,3), MID(`Supporters`.`Phone`,4,3), RIGHT(`Supporters`.`Phone`,4))" => "Phone",
		"CONCAT_WS('-', LEFT(`Supporters`.`Cell`,3), MID(`Supporters`.`Cell`,4,3), RIGHT(`Supporters`.`Cell`,4))" => "Cell",
		"`Supporters`.`Email`" => "Email",
		"`Supporters`.`Status`" => "Status",
		"`Supporters`.`ContactMethod`" => "ContactMethod",
		"`Supporters`.`TotalDonated`" => "TotalDonated",
		"`Supporters`.`TotalMatched`" => "TotalMatched",
		"`Supporters`.`Name`" => "Name",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Supporters`.`ID`" => "ID",
		"`Supporters`.`FirstName`" => "First Name",
		"`Supporters`.`LastName`" => "Last Name",
		"`Supporters`.`SpouseName`" => "Spouse Name",
		"`Supporters`.`Address1`" => "Address1",
		"`Supporters`.`Address2`" => "Address2",
		"`Supporters`.`City`" => "City",
		"`Supporters`.`State`" => "State",
		"`Supporters`.`Zip`" => "Zip",
		"`Supporters`.`Country`" => "Country",
		"`Supporters`.`Phone`" => "Phone",
		"`Supporters`.`Cell`" => "Cell",
		"`Supporters`.`Email`" => "Email",
		"`Supporters`.`Status`" => "Status",
		"`Supporters`.`ContactMethod`" => "Contact Method",
		"`Supporters`.`TotalDonated`" => "Total Donated",
		"`Supporters`.`TotalMatched`" => "Total Matched",
		"`Supporters`.`Name`" => "Name",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Supporters`.`ID`" => "ID",
		"`Supporters`.`FirstName`" => "FirstName",
		"`Supporters`.`LastName`" => "LastName",
		"`Supporters`.`SpouseName`" => "SpouseName",
		"`Supporters`.`Address1`" => "Address1",
		"`Supporters`.`Address2`" => "Address2",
		"`Supporters`.`City`" => "City",
		"`Supporters`.`State`" => "State",
		"`Supporters`.`Zip`" => "Zip",
		"`Supporters`.`Country`" => "Country",
		"CONCAT_WS('-', LEFT(`Supporters`.`Phone`,3), MID(`Supporters`.`Phone`,4,3), RIGHT(`Supporters`.`Phone`,4))" => "Phone",
		"CONCAT_WS('-', LEFT(`Supporters`.`Cell`,3), MID(`Supporters`.`Cell`,4,3), RIGHT(`Supporters`.`Cell`,4))" => "Cell",
		"`Supporters`.`Email`" => "Email",
		"`Supporters`.`Status`" => "Status",
		"`Supporters`.`ContactMethod`" => "ContactMethod",
		"`Supporters`.`TotalDonated`" => "TotalDonated",
		"`Supporters`.`TotalMatched`" => "TotalMatched",
		"`Supporters`.`Name`" => "Name",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`Supporters` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 50;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Supporters_view.php';
	$x->RedirectAfterInsert = 'Supporters_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Supporters';
	$x->TableIcon = 'resources/table_icons/32Px - 002.png';
	$x->PrimaryKey = '`Supporters`.`ID`';
	$x->DefaultSortField = '3';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 100, 100, 100, ];
	$x->ColCaption = ['First Name', 'Last Name', 'Spouse Name', 'Address1', 'Address2', 'City', 'State', 'Zip', 'Country', 'Phone', 'Cell', 'Email', 'Status', 'Contact Method', 'Total Donated', 'Total Matched', 'Donations', 'Notes', 'Matching Funds', ];
	$x->ColFieldName = ['FirstName', 'LastName', 'SpouseName', 'Address1', 'Address2', 'City', 'State', 'Zip', 'Country', 'Phone', 'Cell', 'Email', 'Status', 'ContactMethod', 'TotalDonated', 'TotalMatched', '%Donations.SupporterID%', '%Notes.SupporterID%', '%MatchingFunds.SupporterID%', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, -1, -1, -1, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Supporters_templateTV.html';
	$x->SelectedTemplate = 'templates/Supporters_templateTVS.html';
	$x->TemplateDV = 'templates/Supporters_templateDV.html';
	$x->TemplateDVP = 'templates/Supporters_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Supporters_init
	$render = true;
	if(function_exists('Supporters_init')) {
		$args = [];
		$render = Supporters_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Supporters_header
	$headerCode = '';
	if(function_exists('Supporters_header')) {
		$args = [];
		$headerCode = Supporters_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Supporters_footer
	$footerCode = '';
	if(function_exists('Supporters_footer')) {
		$args = [];
		$footerCode = Supporters_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
